### PR TITLE
Update references for Ankaa-9Q-3

### PR DESCRIPTION
**Pull request by kalzoo**
Now that Ankaa-9Q-3 is online, this updates the documentation to reflect it in all the places where Ankaa-2 once was. 

See [Ankaa-2 removal](https://github.com/MicrosoftDocs/quantum-docs/commit/5e5f416ba9acdaf7b94e83217adf3291df7fb68d) for comparison.

~~Note: this should not be merged until confirming that the SDK supports Ankaa-9Q-3 and that the example is valid~~ [Good to go](https://github.com/microsoft/azure-quantum-python/blob/b031de3f8850c7926d42e48462fcf352f7f50d3a/azure-quantum/azure/quantum/target/rigetti/target.py#L32)

### CODE REVIEW

**Comment by Jak-MS** [comment]
@Bradben @SoniaLopezBravo - can you review the changes to your documents and approve/sign off or request revisions (as necessary) . thanks!

**Comment by Jak-MS** [comment]
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by Bradben — APPROVED** [review]
Thanks!

**Comment by Bradben** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@SoniaLopezBravo - can you review the changes to your article? or does @Bradben 's approval cover that article as well? thanks

**Comment by Bradben** [comment]
@Jak-MS - Sonia is out of the office today, good ahead and merge this on my approval. Thanks!

**Pull request merged**
