### PR TITLE
update Quantinuum eHQCs

### PR DESCRIPTION
**Pull request by mlk621**
update Quantinuum eHQCs to match 10x HQCs pricing model

### CODE REVIEW

**Comment by tedhudek** [comment]
Docs Build status updates of commit _[e2dd483](https://github.com/mlk621/quantum-docs/commits/e2dd4830ba438a1422ea569b2cc0d7c2304161fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/includes/pricing-qc.md](https://github.com/mlk621/quantum-docs/blob/main/articles/includes/pricing-qc.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/776a9f04-28cf-7639-37fb-77d3aae09b34/202208082018461336-562/BuildReport?accessString=7dc757fe28c12e8a462fb3160ba56dedb62108ebab0ad28e28c4172562472426).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/776a9f04-28cf-7639-37fb-77d3aae09b34?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by mlk621** [comment]
@tedhudek

**Comment by Jak-MS** [comment]
@SoniaLopezBravo 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by tedhudek** [comment]
Docs Build status updates of commit _[938c066](https://github.com/mlk621/quantum-docs/commits/938c066a8d125a33f897bff560bd588d60b077fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/includes/pricing-qc.md](https://github.com/mlk621/quantum-docs/blob/main/articles/includes/pricing-qc.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/776a9f04-28cf-7639-37fb-77d3aae09b34/202208091454462579-562/BuildReport?accessString=0140a767f886ebfdb6c6ba64907d68f175b56e2ec9973e677c958792624058f4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/776a9f04-28cf-7639-37fb-77d3aae09b34?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by SoniaLopezBravo — APPROVED** [review]

**Comment by SoniaLopezBravo** [comment]
#sign-off

**Comment by PRMerger4** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @

**Comment by SoniaLopezBravo** [comment]
@mlk621 is this ready to merge?

**Comment by mlk621** [comment]
@SoniaLopezBravo Yes, it is ready to merge! I see for some reason the #sign-off tag didn't work above, not sure why...

**Comment by PRMerger15** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @

**Comment by Jak-MS** [comment]
@mlk621 @SoniaLopezBravo - is there a pricing page? (normally pricing information is not permitted on Docs - which should be technical information). Since this PR doesn't update the pricing information already listed on the page, I'll go ahead and merge the PR, but in the future if you can link to a single, pricing page that is not in docs, that would be best.  For example, Azure docs all link to a separate page: https://azure.microsoft.com/en-us/pricing/calculator/ whenever pricing is mentioned.) 

Thanks.

**Comment by tedhudek** [comment]
Docs Build status updates of commit _[938c066](https://github.com/mlk621/quantum-docs/commits/938c066a8d125a33f897bff560bd588d60b077fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/includes/pricing-qc.md](https://github.com/mlk621/quantum-docs/blob/main/articles/includes/pricing-qc.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/776a9f04-28cf-7639-37fb-77d3aae09b34/202208092043592535-562/BuildReport?accessString=f7d802756114339659aa09c0e65cb894772c1ece124b8df679b5da7a3f02ebb4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/776a9f04-28cf-7639-37fb-77d3aae09b34?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by mlk621** [comment]
Hi @Jak-MS, there is a pricing page! It is here: https://docs.microsoft.com/en-us/azure/quantum/pricing?tabs=tabid-AQcredits%2Ctabid-AQcreditsQ%2Ctabid-payasgo%2Ctabid-learndevelop&pivots=ide-computing. Specifically I needed to edit the amount of eHQCs under the Standard and Premium subscriptions for Quantinuum, which in the repo was the `pricing-qc.md` file under the `articles/includes` folder, which gets linked to the `pricing.md` file in the `articles` folder. I made a few other edits (for example HQC = H-System Quantum Credits).

**Comment by SoniaLopezBravo** [comment]
Hi @Jak-MS! Yes, as @mlk621 mentioned before there is a pricing page since the Azure Quantum 3-rd party providers and how they bill users are separate from Azure pricing. However, for calculating things like storage blob would be a good idea to link to the calculator. I'll do that.

**Comment by Jak-MS** [comment]
@mlk621 @SoniaLopezBravo - I wasn't saying you should or need to link to the Azure pricing calculator, although if it's helpful to customers you can certainly do that.  I was pointing out that for _other_ services with technical documentation on docs.microsoft.com the criteria prohibit the publication of actual prices. This is to prevent customer confusion when there is a price change and multiple pages need to be updated (and there is often a delay in making the changes). That said, it's possible that quantum-docs and quantum-doc-private may have (or need) an exception to this policy.

**Pull request merged**
