### PR TITLE
Honeywell provider deprecation

### PR DESCRIPTION
**Pull request by vxfield**
### Context
In November 2021, Honeywell became Quantinuum: Press release: [Quantinuum is a result of the combination of two global leaders in quantum computing: Honeywell Quantum Solutions and Cambridge Quantum](https://www.quantinuum.com/pressrelease/introducing-quantinuum)

In February/March 2022, Azure Quantum started supporting the Quantinuum provider and targets.

### This PR
This PR adds updates the documentation saying that we no longer support the Honeywell provider and customers need to use Quantinuum provider instead.
Also uses the latest Quantinuum target names from https://learn.microsoft.com/en-us/azure/quantum/provider-quantinuum

### CODE REVIEW

**Comment by tedhudek** [comment]
Learn Build status updates of commit _[c41c280](https://github.com/MicrosoftDocs/quantum-docs/commits/c41c280815d07588e8546e1cf8a727afb8b19a71)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/concepts-qir.md](https://github.com/MicrosoftDocs/quantum-docs/blob/xfield/remove-honeywell/articles/concepts-qir.md) | :white_check_mark:Succeeded | |
[articles/includes/pricing-qc.md](https://github.com/MicrosoftDocs/quantum-docs/blob/xfield/remove-honeywell/articles/includes/pricing-qc.md) | :white_check_mark:Succeeded | |
[articles/provider-honeywell.md](https://github.com/MicrosoftDocs/quantum-docs/blob/xfield/remove-honeywell/articles/provider-honeywell.md) | :white_check_mark:Succeeded | |
[articles/provider-honeywell-migration-guide.md](https://github.com/MicrosoftDocs/quantum-docs/blob/xfield/remove-honeywell/articles/provider-honeywell-migration-guide.md) | :white_check_mark:Succeeded | |
[articles/provider-quantinuum.md](https://github.com/MicrosoftDocs/quantum-docs/blob/xfield/remove-honeywell/articles/provider-quantinuum.md) | :white_check_mark:Succeeded | |
[articles/provider-support-honeywell.md](https://github.com/MicrosoftDocs/quantum-docs/blob/xfield/remove-honeywell/articles/provider-support-honeywell.md) | :white_check_mark:Succeeded | |
[articles/qc-target-list.md](https://github.com/MicrosoftDocs/quantum-docs/blob/xfield/remove-honeywell/articles/qc-target-list.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/776a9f04-28cf-7639-37fb-77d3aae09b34/202210132011059929-571/BuildReport?accessString=318e908f10a2df381e862785f042c98349b9bcdb77cd55328d9ed46665e7c2a4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/776a9f04-28cf-7639-37fb-77d3aae09b34?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Review by Bradben — APPROVED** [review]
Looks great, thanks!

**Comment by jborsecnik** [comment]
@SoniaLopezBravo, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by SoniaLopezBravo — APPROVED** [review]

**Comment by SoniaLopezBravo** [comment]
#sign-off

**Comment by jborsecnik** [comment]
@soniaLopezBravo, @vxfield, note that this doesn't show as a link on GitHub preview. Is the link or link format not correct? 

`please check the [migration guide to switch to the Quantinuum provider](xref:microsoft.quantum.providers.honeywell.migration)`

(three instances)

OR, is this a preview quirk? If so, these changes could be made in the private repo so we get validation and staging views.

**Comment by Bradben** [comment]
That's the correct link - the public repo might not have access to the xref database.

**Comment by tedhudek** [comment]
To add to what Brad said, those xref targets must match a uid metadata on the Learn site.  In this case, `xref:microsoft.quantum.providers.honeywell.migration` is the uid for one of the files in this PR: articles/provider-honeywell-migration-guide.md

**Comment by vxfield** [comment]
Thanks all. So just to confirm, all is good and the cross-ref link is correct, right?

**Comment by Bradben** [comment]
Correct.

**Comment by tedhudek** [comment]
Learn Build status updates of commit _[72ed35f](https://github.com/MicrosoftDocs/quantum-docs/commits/72ed35f20ff847811c29c3c019499c22ff781c2a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/concepts-qir.md](https://github.com/MicrosoftDocs/quantum-docs/blob/xfield/remove-honeywell/articles/concepts-qir.md) | :white_check_mark:Succeeded | |
[articles/includes/pricing-qc.md](https://github.com/MicrosoftDocs/quantum-docs/blob/xfield/remove-honeywell/articles/includes/pricing-qc.md) | :white_check_mark:Succeeded | |
[articles/provider-honeywell.md](https://github.com/MicrosoftDocs/quantum-docs/blob/xfield/remove-honeywell/articles/provider-honeywell.md) | :white_check_mark:Succeeded | |
[articles/provider-honeywell-migration-guide.md](https://github.com/MicrosoftDocs/quantum-docs/blob/xfield/remove-honeywell/articles/provider-honeywell-migration-guide.md) | :white_check_mark:Succeeded | |
[articles/provider-quantinuum.md](https://github.com/MicrosoftDocs/quantum-docs/blob/xfield/remove-honeywell/articles/provider-quantinuum.md) | :white_check_mark:Succeeded | |
[articles/provider-support-honeywell.md](https://github.com/MicrosoftDocs/quantum-docs/blob/xfield/remove-honeywell/articles/provider-support-honeywell.md) | :white_check_mark:Succeeded | |
[articles/qc-target-list.md](https://github.com/MicrosoftDocs/quantum-docs/blob/xfield/remove-honeywell/articles/qc-target-list.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/776a9f04-28cf-7639-37fb-77d3aae09b34/202210140056429033-571/BuildReport?accessString=777d9c18e075d4539515d8e9429883f07e4137cf769063b6160dbb3ec31c5573).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/776a9f04-28cf-7639-37fb-77d3aae09b34?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Pull request merged**
