### PR TITLE
Fix several broken sentences/links in libraries docs

### PR DESCRIPTION
**Pull request by tcNickolas**

### CODE REVIEW

**Review by dphansen — CHANGES_REQUESTED** [review]
Please update `ms.date` in the metadata to ensure doc freshness. Also, going forward, As an MSFT FTE, please use the `quantum-docs-private` repo to get Acrolinx and preview link support. Thank you.

**Comment by tcNickolas** [comment]
Do these changes warrant a date update? They don't describe any new functionality or even add new content about existing functionality, they just fix broken sentences.

May I suggest adding information about the quantum-docs-private repo to the "About" section of this repo? I spent more time with the quantum-docs-pr repo than with the current setup, and the links from the documentation lead to this repo, so I'm prone to getting lost. Having an "About" section saying something like "Public repo for /azure/quantum documentation. For private repo, see quantum-docs-private (MS FTE only)" would be very helpful.

**Comment by dphansen** [comment]
@tcNickolas Yes, every change warrants an update of `ms.date`. I'm not sure if I can add a note about the difference repos to an About section, but I will look into that.

**Comment by tcNickolas** [comment]
Anybody with the admin access to the repo can edit the About section here:
image

Let me know if you'd like me to help!

**Comment by tcNickolas** [comment]
I updated the dates in each page

**Review by dphansen — APPROVED** [review]

**Comment by tcNickolas** [comment]
@dphansen Shall I merge this PR? I'm not sure what's the protocol on this repo

**Comment by dphansen** [comment]
@tcNickolas Yes, please. Thank you.

**Pull request merged**
