### PR TITLE
(WIP) What is AQ - updates 

### PR DESCRIPTION
**Pull request by Bradben**
#hold-off

### CODE REVIEW

**Comment by PRMerger15** [comment]
@Bradben : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by dphansen** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@dphansen: I'm sorry - only the author of this article, @cjgronlund, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Pull request closed without merging**
