### PR TITLE
update reference to technical specs to mention data and how to cite use of QTM HW

### PR DESCRIPTION
**Pull request by mlk621-qtm**

### CODE REVIEW

**Comment by tedhudek** [comment]
Learn Build status updates of commit _[1529cea](https://github.com/mlk621-qtm/quantum-docs/commits/1529cea1d60d643918c0aaab62ab9af106c42357)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/provider-quantinuum.md](https://github.com/mlk621-qtm/quantum-docs/blob/main/articles/provider-quantinuum.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/776a9f04-28cf-7639-37fb-77d3aae09b34/202211231931371857-574/BuildReport?accessString=641f97d949772e59b9745dfc73b1bdc459192ed06d9ae6ddf8543e5d86db3d9e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/776a9f04-28cf-7639-37fb-77d3aae09b34?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by Jak-MS** [comment]
@Bradben 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by Bradben — APPROVED** [review]
Looks good, thanks!

**Comment by Bradben** [comment]
#sign-off

**Pull request merged**
