### PR TITLE
Update page structure for Q# language docs

### PR DESCRIPTION
**Pull request by samarsha**
The page structure for the Q# language docs in microsoft/qsharp-language has changed:

- PartialApplication.md was renamed to Closures.md
microsoft/qsharp-language#136
- TypeInference.md now has content (it used to be blank)
microsoft/qsharp-language#140

### CODE REVIEW

**Comment by PRMerger10** [comment]
@samarsha : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by bettinaheim — APPROVED** [review]

**Comment by Jak-MS** [comment]
@samarsha @bettinaheim - as far as i can tell without the private repo tools, there's only one thing missing from this PR. Because you're changing a file name, you'll need to add a redirect entry in the .openpublishing.redirection.json file . 

After you've made the new entry and added the updated file to the PR, sign off again and we'll merge this. thanks.

#hold-off

**Comment by PRMerger14** [comment]
@samarsha : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@samarsha @bettinaheim - looks good. please check the rendering post-publish to make sure the include etc are working as intended. merging now.

**Pull request merged**
