### PR TITLE
Updates to SlcTerms and Protobuf availability

### PR DESCRIPTION
**Pull request by frtibble**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@frtibble : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@george-moussa @danielstocker @Bradben 

Can you review the proposed changes? Due to the extent of the changes, they should be moved into the **private repo** to benefit from staging and validation checks.

*IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

Thanks!
#label:"aq-pr-triaged"
#assign:@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger15** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: microsoftdocs/public-repo-pr-review-team

**Comment by PRMerger3** [comment]
@frtibble : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@frtibble : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by frtibble** [comment]
Closing this PR as I have opened an equivalent PR in the private repo. Thanks!

**Pull request closed without merging**
