### PR TITLE
Add new param to tabu solver

### PR DESCRIPTION
**Pull request by Bradben**
@dphansen, @haohaiyu

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @Bradben - It looks like you might be internal to Microsoft, because you opened a PR in the private repo (I don't find you in internal people-finder resources, though). Also, article ownership typically isn't updated in the public repo. If you're Microsoft-internal, would you make this update in the private repo? Thanks.

**Comment by cjgronlund** [comment]
Approved by manager @cjgronlund 
#sign-off

**Comment by PRMerger13** [comment]
@cjgronlund: I'm sorry - only the author of this article, @adelebai, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by dphansen** [comment]
#hold-off

**Pull request merged**
