### PR TITLE
Document C# full state simulator constructor parameters

### LINKED ISSUE #181: Document throwOnReleasingQubitsNotInZeroState parameter in full state simulator docs
The page documents other constructor parameters, but not this one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c36e49-20c7-4713-d3d7-7faa5e3f0c7e
* Version Independent ID: 2b067d7a-9b68-8dfd-624b-dad1d8df5588
* Content: [Full state quantum simulator - Quantum Development Kit - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/machines/full-state-simulator)
* Content Source: [articles/user-guide/machines/full-state-simulator.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/machines/full-state-simulator.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @anpaz
* Microsoft Alias: **anpaz**

### PR DESCRIPTION
**Pull request by dime10**
Closes #181

### CODE REVIEW

**Review by SoniaLopezBravo — COMMENTED** [review]
Looks good!! Can I ask you where did you find the documentation for `throwOnReleasingQubitsNotInZeroState` parameter? @imi-hub and I were looking at this issue before and we couldn't figure it out.

**Comment by dime10** [comment]
Sure, I had a look at the source code. The simulators are located over at https://github.com/microsoft/qsharp-runtime.

**Comment by SoniaLopezBravo** [comment]
> Sure, I had a look at the source code. The simulators are located over at https://github.com/microsoft/qsharp-runtime.

Thanks! Which folder exactly? I am not able to find it.

**Comment by dime10** [comment]
The constructor is here: https://github.com/microsoft/qsharp-runtime/blob/main/src/Simulation/Simulators/QuantumSimulator/QuantumSimulator.cs

**Review by SoniaLopezBravo — APPROVED** [review]

**Pull request merged**
