### PR TITLE
Add seed parameter to 1QBit solver documentation

### PR DESCRIPTION
**Pull request by Estella-Wang-1qbit**
- Add `seed` parameter to every solvers

### CODE REVIEW

**Comment by Estella-Wang-1qbit** [comment]
Hi @Mobius5150 ,
I want to add you as the reviewer, but I couldn't do it somehow. Please take a look at this PR when you have some time. Thanks.

**Review by Mobius5150 — APPROVED** [review]

**Comment by Mobius5150** [comment]
@Estella-Wang-1qbit thanks for sending this! Would you mind rebasing on top of the latest changes to make sure I don't miss anything? Thanks!

**Comment by Estella-Wang-1qbit** [comment]
> @Estella-Wang-1qbit thanks for sending this! Would you mind rebasing on top of the latest changes to make sure I don't miss anything? Thanks!

Hi @Mobius5150,
I have rebased on top of the latest changes and please take a look before I merge it. Thanks!

**Comment by Estella-Wang-1qbit** [comment]
Hi @Mobius5150 ,

It's been a while and I see this PR hasn't been merged in. Could you please merge it in?

**Comment by Estella-Wang-1qbit** [comment]
Hi @Mobius5150, any updates on this PR?

**Pull request merged**
