### PR TITLE
Fix QDK Jupyter install URL

### LINKED ISSUE #167: URL for installation guide is incorrect.
The page at https://docs.microsoft.com/azure/quantum/install-jupyter-qkd incorrectly has "QKD" (quantum key distribution) instead of "QDK" (Quantum Development Kit).

### PR DESCRIPTION
**Pull request by dime10**
Rename `articles/install-jupyter-qkd.md` to `articles/install-jupyter-qdk.md`

Redirect [here](https://github.com/MicrosoftDocs/azure-reference-other-pr/pull/710)

Closes #167

### CODE REVIEW

**Review by SoniaLopezBravo — APPROVED** [review]

**Comment by tcNickolas** [comment]
@dime10 @SoniaLopezBravo When you change a URL of a page in the documentation, please add a redirect from the old URL to the new one. Otherwise all external links that used to point to the old URL break, (and installation guides have a lot of external links pointing to them) which makes a lot of things more painful than they should be (see https://github.com/microsoft/QuantumKatas/pull/622/files for an example). 

Please follow up with @KittyYeungQ  for the right procedure for this, I know we have documentation on how to do that but I can't locate it at the moment.

**Comment by Bradben** [comment]
> @dime10 @SoniaLopezBravo When you change a URL of a page in the documentation, please add a redirect from the old URL to the new one. Otherwise all external links that used to point to the old URL break, (and installation guides have a lot of external links pointing to them) which makes a lot of things more painful than they should be (see https://github.com/microsoft/QuantumKatas/pull/622/files for an example).
> 
> Please follow up with @KittyYeungQ for the right procedure for this, I know we have documentation on how to do that but I can't locate it at the moment.

David did add the redirect for the file rename ([here](https://github.com/MicrosoftDocs/azure-reference-other-pr/pull/710)), but only for the old docset. I missed that on my review - my fault. I've added [this PR](https://github.com/MicrosoftDocs/azure-reference-other-pr/pull/715) to also redirect it from the last URL in the current docset.

**Comment by KittyYeungQ** [comment]
@Bradben Do you mean this one that is merged in README.md https://github.com/MicrosoftDocs/quantum-docs/pull/115 @dime10 @SoniaLopezBravo

**Comment by tcNickolas** [comment]
@KittyYeungQ @Bradben What is the status of this redirect? I still see https://docs.microsoft.com/en-us/azure/quantum/install-jupyter-qkd giving 404 instead of redirecting to the new page.

**Comment by Bradben** [comment]
> @KittyYeungQ @Bradben What is the status of this redirect? I still see https://docs.microsoft.com/en-us/azure/quantum/install-jupyter-qkd giving 404 instead of redirecting to the new page.

It's fixed in [this PR](https://github.com/MicrosoftDocs/azure-reference-other-pr/pull/715) - the azure-reference-other-pr repo syncs weekly on Tuesdays, so it will be live tomorrow.

**Pull request merged**
