### PR TITLE
Adding examples on how to filter list_jobs

### PR DESCRIPTION
**Pull request by adelebai**
Adding examples on how to filter list_jobs

### CODE REVIEW

**Review by danielstocker — COMMENTED** [review]
Let's include a note before we go into the different types of filtering to clarify Python SDK version requirements

**Comment by adelebai** [comment]
> Let's include a note before we go into the different types of filtering to clarify Python SDK version requirements

Do you mean we add a line in the documentation saying "this feature only available on ver x.xx.xx+"?

**Comment by danielstocker** [comment]
> > Let's include a note before we go into the different types of filtering to clarify Python SDK version requirements
> 
> Do you mean we add a line in the documentation saying "this feature only available on ver x.xx.xx+"?

Yes let's do that for now. You can possibly use the > [!NOTE] element for that and just say something like 

"Filtering is available in version x.xx.xxxx and newer of the Python SDK" 

That means people on older versions know to update

**Review by danielstocker — APPROVED** [review]

**Review by danielstocker — APPROVED** [review]

**Comment by danielstocker** [comment]
Oh turns out I don't have write permission. @SoniaLopezBravo I think this one is good to go

**Review by SoniaLopezBravo — APPROVED** [review]
Thanks for these updates!

**Pull request merged**
